# chroma-server/render.yaml
services:
  - type: web
    name: tesfa-chroma
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: IS_PERSISTENT
        value: "true"
    disk:
      name: chroma-data
      mountPath: /chroma/chroma-data
      sizeGB: 1